default:
  image: themattrix/tox

stages:
  - test
  - docs
  - build
  - deploy

test-check:
  stage: test
  script:
    - tox -v -e check

test-py36-nocov:
  stage: test
  script:
    - tox -v -e 3.6-nocov

test-py37-nocov:
  stage: test
  script:
    - tox -v -e 3.7-nocov

test-py37-cover:
  stage: test
  script:
    - tox -v -e 3.7-cover

test-py38-nocov:
  stage: test
  script:
    - tox -v -e 3.8-nocov

docs:
  stage: docs
  script: tox -v -e docs

build:
  stage: build
  script: python setup.py sdist bdist_wheel

deploy:
  stage: deploy
  script: twine upload -r testpypi --non-interactive dist/*