default:
  image: $CI_REGISTRY/atteq/z-service-layer/zsl/tox-env@sha256:7462f5ed2d26df593927c0c15aa1dff2e600489b25d176aaa57af5b527b5a673

stages:
  - test
  - docs
  - mirror
  - build
  - deploy

test-check:
  stage: test
  script:
    - tox -v -e check

test-py38-nocov:
  stage: test
  script:
    - tox -v -e 3.8-nocov

test-py38-cover:
  stage: test
  script:
    - tox -v -e 3.8-cover

test-py310-nocov:
  stage: test
  script:
    - tox -v -e 3.10-nocov

test-py311-nocov:
  stage: test
  script:
    - tox -v -e 3.11-nocov

docs:
  stage: docs
  script: tox -v -e docs

mirror-to-github:
  stage: mirror
  script:
    # Set up GitHub details
    - git config --global user.email "firm@atteq.com"
    - git config --global user.name "Atteq"

    # Add GitHub as a remote using the access token and push
    - git remote remove github || true
    - git remote add github https://x-access-token:$GITHUB_ACCESS_TOKEN@github.com/AtteqCom/zsl.git || true
    - git push github HEAD:master --tags

  rules:
    # Runs for master branch
    - if: '$CI_COMMIT_REF_NAME == "master"'
    # Runs for tags with the desired format
    - if: '$CI_COMMIT_REF_NAME =~ /^\d+\.\d+\.\d+$/'

build:
  stage: build
  script: python3 setup.py sdist bdist_wheel
  only:
    - tags
  except:
    - branches
  artifacts:
    paths:
      - dist/*
    expire_in: 1 week

deploy:
  stage: deploy
  script: twine upload --non-interactive dist/*
  only:
    - tags
  except:
    - branches
