default:
  image: $CI_REGISTRY/atteq/z-service-layer/zsl/tox-env@sha256:b73bdde18840315fc1ac8e03ed7d1d46a0eced86bc527208be30ac65b7ab7243

stages:
  - test
  - docs
  - build
  - deploy

test-check:
  stage: test
  script:
    - tox -v -e check

test-py38-nocov:
  stage: test
  script:
    - tox -v -e 3.8-nocov

test-py38-cover:
  stage: test
  script:
    - tox -v -e 3.8-cover

test-py310-nocov:
  stage: test
  script:
    - tox -v -e 3.10-nocov

test-py311-nocov:
  stage: test
  script:
    - tox -v -e 3.11-nocov

docs:
  stage: docs
  script: tox -v -e docs

build:
  stage: build
  script: python3 setup.py sdist bdist_wheel
  only:
    - tags
  except:
    - branches
  artifacts:
    paths:
      - dist/*
    expire_in: 1 week

deploy:
  stage: deploy
  script: twine upload --non-interactive dist/*
  only:
    - tags
  except:
    - branches
