default:
  image: themattrix/tox

stages:
  - test
  - extra

test:
  stage: test
  script:
    - tox

test-py36-nocov:
  stage: test
  script:
    - tox -v -e 3.6-nocov

test-py37-nocov:
  stage: test
  script:
    - tox -v -e 3.7-nocov


test-py37-cover:
  stage: test
  script:
    - tox -v -e 3.7-cover

test-py38-nocov:
  stage: test
  script:
    - tox -v -e 3.8-nocov
docs:
  stage: extra
  script: tox -v -e docs