language: python
python:
- '2.7'
- '3.6'
install: pip install -r requirements.txt
script: python -m unittest discover tests '*_test.py'
deploy:
  provider: pypi
  user: morihladko
  server: https://testpypi.python.org/pypi
  password:
    secure: In0JdnQdIFku0a2qjjSGpjf504QWOz+W7M7w88xHP3ZtPWhbR2TbQBJ1bQbNrcH+pEFpvOrNMkue3IkmqXtiyDcWfVv5+eophXMYl61Ca8fHRuMFpIjGW6TgXY/4+Jw+/ZnxC8VGj5oVl4ml5/52GoVyxAXFqWqcoQBahc4QglxTm7yFZdcn0TsSNguJuXIZyH90lx+BjmIaoX+B/e3BOpCJDGqOaAKvpBPjJ3286gS7ghey7+SDMNsd1E3njrwNCCl7L8kQJZIuMxawYJUktzZLFWeVY4UUL98vLgSNOrAvZj6bx8ZL6DfTL0t5eTZIYF41k4AipB78ZajOshX1XLbAWyypx41LRurqTMUXqkUu/5opJqINnqr6KeS0mfm23SnyTbrxjfEhK1uQhSMI/TvUbtds0ii4EwztB38vVILGUhiTY41uaedjQxL9tZc3R0CQVZqUJBl7q15o3zDmLDSwDx2Kan+CP28Ov8/SViarM7HlXLD9oMYfksQbIaJaoXTRDAnXtI1mNxoywC5g5ai/lIPrLJGuI4Ed6cpKR+9vhF6RLe9nxYC4M/UJH2Ogro9dYco3dhwUxx+1OyHjJ6KbiWQdTw7L0fTSanmwAdLLVT0FjhtuuuyGmMoZ0fmcvAQI9nBD6jrvOqogp/S1hfZQLp5DtdESyLiJ6MmJyRw=
  on:
    tags: true
    distributions: sdist bdist_wheel
