language: python
python:
- '2.7'
- '3.6'
install: pip install -r test-requirements.txt
script: python -m unittest discover tests '*_test.py'
deploy:
  provider: pypi
  user: atteq
  password:
    secure: jwWLmWNCwZLWItKNYSC3jax6EM8U5yHWEZacwUlaghkOATvqtCAlBAYk8k4j3lgMJF5zHbySrZqePku9xL2rZCXFnTO7QBA7YUAFSx+v0pfnxtfY5Gg287Mv2vK5hHAFrzuxFPIyL1VOHhVU4VYHDtBIZmT3t0T/FRQargLNwHgbAPHiNn+YEtRJ4Z2+ZZUgSieqx+2IVmbx1BHZrgwbrN3NA4+bkdliA3APJHImh32k15AdmCzyipZKCNtlGQJLgq/hqC32bDlsidBelzVHBYqt1cU915zhxuGpLURrpc67skSgwhhA8zWHiErW5zwJEo/oaLGrdMTM/bGTonF/3BLbBDUSpuWoJ5oGKZvdefxVC85dloEOJfbEUZwxHZ5yiUY6vRK/Pdki7Y1+dx9JjkVpv2gtje2EH1ft2AhKNIEmq8rUUmoDljjkN7D+s6GhLrvdG9mLsv/Cwzu2zRbqmbW3uLzGC4b3VH0yz58KqYpyG5geg66OiuP9SKg7Q/lBmcogru78mTGjtb4s1f2QOIEK1ew3vktpsC1hIM38Lo6icnmCunG1a9MMlwoIONvYXPZ76TrGHWtkPzXpEfk3sHE2Ue+6YVMvRK5hw2GbqpYiImC9m8bsr3rjmw22y02F5HETj4iu9E7AarF5k1pidPkWsr2N0sRpwGBO9LPpE50=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: AtteqCom/zsl
