FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

RUN apt update \
    && apt install -y software-properties-common \
    && add-apt-repository ppa:deadsnakes/ppa \
    && apt update \
    && apt install -y \
        python3.8 \
        python3.8-distutils \
        python3.11 \
        python3-pip \
        git \
    && rm -rf /var/lib/apt/lists/*
RUN pip install \
    tox \
    twine
