#
# 20.04 because of legacy pythons, upgrad when moving to newer ones
#
FROM ubuntu:20.04

RUN apt update
RUN apt install -y software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt update
RUN apt install -y\
    python3.5 \
    python3.6 \
    python3.6-distutils \
    python3.7 \
    python3.7-distutils \
    python3-pip \
    git
RUN pip install \
    tox \
    twine
